export const ADD_NEW_CITY = 'ADD_NEW_CITY';
export const REMOVE_CITY = 'REMOVE_CITY';
export const GET_WEATHER_INFO = 'GET_WEATHER_INFO';
export const WEATHER_REQUEST_FAILED = 'WEATHER_REQUEST_FAILED';